runtime: php73

env_variables:
  APP_ENV: prod
  APP_SECRET: 40fed87bcba3b86c1855cfee81e01d73
  DATABASE_URL: mysql://root:m1-ccm@localhost?unix_socket=/cloudsql/insset:europe-west6:bdd-projet-m1;dbname=prod


handlers:
  # Declare the build and bundles directory as static assets to be served by the
  # App Engine CDN.
  - url: /build
    static_dir: public/build
  - url: /bundles
    static_dir: public/bundles

  # Declare any media files in the public directory as static assets as well.
  - url: /(.*\.(ico|txt|gif|png|jpg))$
    static_files: public/\1
    upload: public/.*\.(ico|txt|gif|png|jpg)$
